# Use the official Node.js 18 image as a base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or pnpm-lock.yaml) to the working directory
COPY package*.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Build the app
RUN npm run build

# Start the app
CMD ["npm", "run", "preview"]
