FROM node:18.12.0-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Build the app
RUN npm run build

# Install serve to serve the static site
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 80

# Serve the static site
CMD ["serve", "-s", "build", "-l", "80"]
